name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add Ondřej PPA
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ondrej/php -y
        sudo apt-get update

    - name: Install PHP 8.4 and Dependencies
      run: |
        sudo apt-get install -y php8.4 php8.4-dev autoconf automake libtool libuv1-dev libhttp-parser-dev libnghttp2-dev libwebsockets-dev libmysqlclient-dev libhiredis-dev
        # Retry php8.4-dev installation if headers are missing
        if [ ! -f /usr/include/php/20240829/Zend/zend_fiber.h ] && [ ! -f /usr/include/php/20240924/Zend/zend_fiber.h ]; then
          sudo apt-get install --reinstall php8.4-dev
        fi

    - name: Debug PHP Environment
      run: |
        php -v
        php-config --version
        php-config --includes
        find /usr/include/php -name zend_fiber.h || echo "zend_fiber.h not found"
        ls -l /usr/include/php/*/Zend/ || echo "No Zend directory found"
        cat berryrt/configure.ac
        ls -l berryrt/m4/ || echo "m4 directory not found"

    - name: Create m4 Directory
      run: |
        mkdir -p berryrt/m4

    - name: Build berryrt
      run: |
        cd berryrt
        autoreconf -fi
        phpize
        ./configure --with-php-config=$(which php-config) CFLAGS="-I/usr/include/php/20240829 -I/usr/include/php/20240829/Zend -I/usr/include/php/20240924 -I/usr/include/php/20240924/Zend" LDFLAGS="-L/usr/lib"
        make
        sudo make install
        cd ..

    - name: Install Composer Dependencies
      run: |
        cd berryphp
        composer install

    - name: Run Tests
      run: |
        cd berryphp
        ../run.sh tests/composer.php &
        sleep 2
        curl http://localhost:3000
        ../run.sh tests/view.php &
        sleep 2
        curl http://localhost:3000